[package]
name = "algotrade"
version = "0.1.0"
edition = "2024"
authors = ["Paolo Angioletti <paolo.angioletti@gmail.com>"]
description = "Algorithmic trading for financial applications"

[dependencies]
